
# ----------------------------------------------------------------------
# JupyterLab Notebook for analyzing E3SM-ELM land model output
#
# This adds the example NGEE-Arctic notebook scripts to the base container
# ----------------------------------------------------------------------

# grab the jupyter-lab container
FROM serbinsh/ngeearctic_elm_containers:ngeearctic_jupyterlab_3.3.2
LABEL maintainer.name="Shawn P. Serbin" \
      maintainer.email="sserbin@bnl.gov" \
      author.name="Shawn P. Serbin" \
      author.email="sserbin@bnl.gov" \
      description="ELM Analysis Jupyter-Lab Container"

ENV REPOSITORY_RAW_URL=https://raw.githubusercontent.com/TESTgroup-BNL/ngeearctic_elm_containers

# Copy in example plotting scripts for use with model output
# add Ben Sulman's matplotlib plotting ascetics defaults
RUN cd "/home/${NB_USER}/scripts" \
   && wget $REPOSITORY_RAW_URL/main/scripts/elm_scripts/plotting/plot_KG64_ELM_output.py \
   && chmod 775 plot_KG64_ELM_output.py \
   && wget $REPOSITORY_RAW_URL/main/scripts/elm_scripts/plotting/plot_ELM_output.py \
   && chmod 775 plot_ELM_output.py \
   && cd "/home/${NB_USER}" \
   && mkdir -p "/home/${NB_USER}/.config/matplotlib" \
   && cd "/home/${NB_USER}/.config/matplotlib" \
   && wget $REPOSITORY_RAW_URL/main/scripts/elm_scripts/plotting/matplotlibrc \
   && cd "/home/${NB_USER}" \
   && fix-permissions "/home/${NB_USER}"

# Add example jupyter notebook scripts here
RUN cd "/home/${NB_USER}/scripts" \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_variable.ipynb \
   && chmod 775 plot_ELM_variable.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_variable_2D.ipynb \
   && chmod 775 plot_ELM_variable_2D.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_output.ipynb \
   && chmod 775 plot_ELM_output.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_radiation.ipynb \
   && chmod 775 plot_ELM_radiation.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_moisture_temperature.ipynb \
   && chmod 775 plot_moisture_temperature.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_soil_BGC.ipynb \
   && chmod 775 plot_soil_BGC.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_veg_data.ipynb \
   && chmod 775 plot_veg_data.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_ensembles.ipynb \
   && chmod 775 plot_ELM_ensembles.ipynb \
   && wget $REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_compare_cases.ipynb \
   && chmod 775 plot_ELM_compare_cases.ipynb

# Setup default user, when enter docker container
USER ${NB_UID}
WORKDIR "${HOME}"

# EOF